components:
  schemas:
    Error:
      properties:
        error:
          description: "\u0421\u043E\u043E\u0431\u0449\u0435\u043D\u0438\u0435 \u043E\
            \u0431 \u043E\u0448\u0438\u0431\u043A\u0435"
          example: Invalid input parameter number
          type: string
      required:
      - error
      type: object
    Input:
      properties:
        number:
          description: "\u0427\u0438\u0441\u043B\u043E"
          example: 5
          type: integer
        power:
          description: "\u0421\u0442\u0435\u043F\u0435\u043D\u044C"
          example: 2
          type: integer
      required:
      - number
      - power
      type: object
    Output:
      properties:
        result:
          description: "\u0420\u0435\u0437\u0443\u043B\u044C\u0442\u0430\u0442"
          example: 25
          type: integer
      required:
      - result
      type: object
info:
  title: My App
  version: 1.0.0
openapi: 3.0.3
paths:
  /docs/dist/{filename}: {}
  /docs/{path}: {}
  /power:
    get:
      parameters:
      - description: "\u0421\u0442\u0435\u043F\u0435\u043D\u044C"
        in: query
        name: power
        required: true
        schema:
          example: 2
          type: integer
      - description: "\u0427\u0438\u0441\u043B\u043E"
        in: query
        name: number
        required: true
        schema:
          example: 5
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Output'
          description: "\u0420\u0435\u0437\u0443\u043B\u044C\u0442\u0430\u0442 \u0432\
            \u043E\u0437\u0432\u0435\u0434\u0435\u043D\u0438\u044F \u0432 \u0441\u0442\
            \u0435\u043F\u0435\u043D\u044C"
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: "\u041D\u0435 \u043F\u0435\u0440\u0435\u0434\u0430\u043D \u043E\
            \u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\u044B\u0439 \u043F\
            \u0430\u0440\u0430\u043C\u0435\u0442\u0440"
      summary: "\u0412\u043E\u0437\u0432\u043E\u0434\u0438\u0442 \u0447\u0438\u0441\
        \u043B\u043E \u0432 \u0441\u0442\u0435\u043F\u0435\u043D\u044C"
      tags:
      - math
  /swagger: {}
tags:
- description: "\u041C\u0430\u0442\u0435\u043C\u0430\u0442\u0438\u0447\u0435\u0441\
    \u043A\u0438\u0435 \u0444\u0443\u043D\u043A\u0446\u0438\u0438"
  name: math
